# Generated by Django 4.2.4 on 2023-10-20 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('contactList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contactlist')),
            ],
        ),
    ]
